### ISSUE TITLE
backend/config folder missing / error in creating new user

### ISSUE THREAD

**Issue by nicebread** [KL-Psychological-Methodology/ESMira-web#4]
When we copied the ESMira installation folder to the server, we could directly access the frontend website. But creating a new user gave a php error "could not create file" (although permissions were fine).

We realized that the `backend/config` folder was not present. Manually creating this folder solved the problem.

**Comment by SelinaDev** [comment]
Duplicate of #3

**Comment by SelinaDev** [comment]
Thank you, we are aware of this issue. It should be fixed by b9025eb, I just didn't have a chance to include this in a release yet. I'm aiming to do so next week.
